### ISSUE TITLE
Syntax highlighting does't work

### ISSUE THREAD

**Issue by jaskiratr** [ele828/hexo-prism-plugin#25]
Hi,
I'm unable to see any highlighting work. I've configured `config.yml` correctly as well

```
highlight:
  enable: false
  # line_number: true
  # auto_detect: false
  # tab_replace:
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'okaidia'
  line_number: false    # default false
```
**Expectation: .js code in markdown to be highlighted. Below is a screenshot from text editor**
![image](https://user-images.githubusercontent.com/8619877/27250276-95a4b1c6-52f8-11e7-8f8e-4a6399fce492.png)

**Behaviour: No highlighting in the web browser**
![image](https://user-images.githubusercontent.com/8619877/27250279-c0526ee0-52f8-11e7-93c4-d55f1dcc777d.png)

No errors in browser console either. 
Not sure what's going on...
