### ISSUE TITLE
不起作用

### ISSUE THREAD

**Issue by fenglu09** [ele828/hexo-prism-plugin#43]
按照`readme` 安装了插件，不起作用。
设置如下：
```
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess 
  theme: 'okaidia'
  line_number: false    # default false 
```
