### ISSUE TITLE
prism不起作用

### ISSUE THREAD

**Issue by TheNetAdmin** [ele828/hexo-prism-plugin#5]
我尝试将prism_plugin的设置代码插入到`/_config.yml`或者`/theme/some_theme/_config.yml`，但是实际生成的页面并没有prism高亮的代码块

**Comment by sn0wle0pard** [comment]
Did you check  `highlight: enable: false` in `/_config.yml`?  hexo-prism-plugin only work turn false

**Comment by cubesky** [comment]
I turned
```yml
highlight:
  enable: false
```
and add 
```yml
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess 
  theme: 'default'
  line_number: true
```
to `_config.yml` in the site config.
But it doesn't work.
![image](https://cloud.githubusercontent.com/assets/8038511/23034721/af172cbe-f4b7-11e6-931a-90e90f3cf9eb.png)

I try to generate with `hexo clean&hexo g` and `hexo clean&hexo s` it doesn't work.
